services:
  one-api:
    build: .
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data/oneapi:/data
      - ./logs:/app/logs
    environment:
      # 注释掉 SQL_DSN 以使用 SQLite
      # - SQL_DSN=mysql_user:password@tcp(db:3306)/oneapi
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=idasifi39jd8w8fdiejfdae  # 修改为随机字符串
      - TZ=Pacific/Auckland
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    depends_on:
      - redis

  redis:
    image: "${REGISTRY:-docker.io}/redis:latest"
    container_name: redis
    restart: always
    environment:
      - TZ=Pacific/Auckland